# Artificial Intellegence for the Sliding Tile Puzzle

In this project, we will explore the [sliding tile puzzle](https://en.wikipedia.org/wiki/Sliding_puzzle). The sliding tile puzzle is a game similar to the rubicks cube, where the goal is to place the numbered squares in order, given a random initial state. 

In [13]:
# Import libraries needed for later parts. 
import random
import numpy as np
import heapq

First, let's run a bunch of helper functions. These functions are not necessary to learn, but are helpful for later on.

The two functions that may be useful for you:

generate_valid_sliding_tile(n): will generate a solvable n x n sliding tile puzzle
goal(puzzle): will generate the goal state for a given puzzle 

In [14]:
def generate_random_sliding_tile(n):
    ''' Generates a random sliding tile puzzle given the size of the puzzle
        n: the number of rows and columns in the puzzle
    '''
    # Create a list of all the possible numbers
    numbers = list(range(0, n*n))
    
    # Shuffle the list of numbers
    random.shuffle(numbers)
    
    # Shape the random array into a possible puzzle configuration
    tile_array = np.array(numbers).reshape(n, n)

    return tile_array

def check_valid_sliding_tile(puzzle):
    ''' Checks to see if a sliding tile puzzle is valid (not all are)
        Uses some fancy math to see if they are possible
    '''
    def count_inversions(array):
        count = 0
        for i in range(len(array)):
            j = i + 1
            while j < len(array):
                if array[i] > array[j]:
                    count +=1
                j += 1
        return count
    
    def blank_square_row(puzzle):
        for i in range(len(puzzle)):
            if 0 in puzzle[i]:
                return i
    
    x_dim, y_dim = puzzle.shape

    # We are only considering square puzzles
    assert(x_dim == y_dim)
    
    # Flatten the matrix to just an array
    flattened_puzzle = puzzle.flatten()

    # Remove the Empty tile from the array
    flattened_puzzle = flattened_puzzle[flattened_puzzle != 0]
    
    # Get the number of inversions in the array
    inversions = count_inversions(flattened_puzzle)
    
    # Fancy math to see if the puzzle is solvable
    if x_dim % 2 == 0:
       return (blank_square_row(puzzle) + inversions) % 2 == 1
    else:
        return inversions % 2 == 0

def generate_valid_sliding_tile(n):
    ''' Generates a valid sliding tile puzzle given the size of the puzzle
        n: the number of rows and columns in the puzzle
    '''
    if n <= 1:
        raise ValueError("n must be greater than 1")

    # Generate a random puzzle
    puzzle = generate_random_sliding_tile(n)
    while (not check_valid_sliding_tile(puzzle)):
        puzzle = generate_random_sliding_tile(n)
    return puzzle

def goal(puzzle):
    ''' Returns a goal state of a puzzle at a given size'''
    numbers = list(range(1, puzzle.shape[0]*puzzle.shape[1]))
    numbers.append(0)
    return np.array(numbers).reshape(puzzle.shape)

def check_if_in_array(seen, puzzle):
    ''' Checks to see if an element is in an array '''
    for item in seen:
        if (item == puzzle).all():
            return True
    return False

Now that all the helper functions are created. Lets look at the state representation of the puzzle that we are going to solve. Below shows a 2 x 2 sliding tile puzzle, where 0 is the blank space. As we can also see, we want to find the set of moves that will make us get to the goal state.

In [15]:
print('A Random Puzzle\n',generate_valid_sliding_tile(2))
print('Goal State\n',goal(generate_valid_sliding_tile(2)))

A Random Puzzle
 [[3 0]
 [2 1]]
Goal State
 [[1 2]
 [3 0]]


Now that we have our state representation, we need to create the possible actions that we can perform. Thus, we need to create functions to slide up, down, left, or right. If its not possible to slide in that direction, we are just returning False so that we don't worry about it later.

Slide_up is implemented for you as a template. Your job is to implement slide_down, slide_left, and slide_right.

In [16]:
def slide_up(puzzle):
    x_blank_tile, y_blank_tile = np.where(puzzle == 0)
    new_puzzle = puzzle.copy()
    
    # First check to see if the empty tile is in the top row as we can't slide up in that case
    if x_blank_tile == 0:
        return False
    
    # Now lets swap the empty tile with the tile above it
    tile_above = puzzle[x_blank_tile - 1, y_blank_tile]

    new_puzzle[x_blank_tile - 1, y_blank_tile] = 0
    new_puzzle[x_blank_tile, y_blank_tile] = tile_above

    return new_puzzle

def slide_down(puzzle):
    x_blank_tile, y_blank_tile = np.where(puzzle == 0)
    new_puzzle = puzzle.copy()
    
    ''' Start of Answer '''


    ''' End of Answer '''

    return new_puzzle

def slide_left(puzzle):
    x_blank_tile, y_blank_tile = np.where(puzzle == 0)
    new_puzzle = puzzle.copy()
    
    ''' Start of Answer '''

    ''' End of Answer '''

    return new_puzzle

def slide_right(puzzle):
    x_blank_tile, y_blank_tile = np.where(puzzle == 0)
    new_puzzle = puzzle.copy()

    ''' Start of Answer '''
    
    ''' End of Answer '''

    return new_puzzle    

Now, make sure that your sliding is correct by manually checking that you have the right method.

In [17]:
puzzle = generate_valid_sliding_tile(3)

print('starting puzzle\n', puzzle)
print('sliding up\n', slide_up(puzzle))
print('sliding down\n', slide_down(puzzle))
print('sliding left\n', slide_left(puzzle))
print('sliding right\n', slide_right(puzzle))

starting puzzle
 [[3 1 2]
 [5 8 6]
 [7 0 4]]
sliding up
 [[3 1 2]
 [5 0 6]
 [7 8 4]]
sliding down
 False
sliding left
 [[3 1 2]
 [5 8 6]
 [0 7 4]]
sliding right
 [[3 1 2]
 [5 8 6]
 [7 4 0]]


Now that we have our actions, we also need to see if our puzzle is solved. 

Hint: Use the goal function from the helper functions

In [18]:
def check_solved(puzzle):
    ''' Checks to see if the puzzle is solved 
        Input: the current sliding tile puzzle
        Output: True if the puzzle is solved, False otherwise
    '''

    ''' Start of Answer '''
    ''' End of Answer '''
    pass

Now we need to actually solve the puzzle. First, we are going to use a breadth first search, which will provide an optimal solution by exhaustively checking all possibilities.

Most of the search function is already implemented. You need to fill in some sections.

In [19]:
# Perform a Breadth First Search of the Sliding Tile Puzzle
def bfs_sliding_tile(puzzle):
    ''' Performs a Breadth First Search of the Sliding Tile Puzzle '''
    # Create a queue to perform the BFS
    seen = []
    to_visit = [((), puzzle)]
    while len(to_visit) > 0:
        # Get the current state of the puzzle
        current_path, current_puzzle = to_visit.pop(0)
        
        # Check to see if the puzzle has been previously visited, as we don't want to recheck something
        if check_if_in_array(seen, current_puzzle):
            continue

        
        # Check to see if the puzzle is solved, if its solved then we should return our path, otherwise we should do nothing

        ''' Start of Answer '''
        ''' End of Answer '''

        # Add the puzzle to the seen set, this is so we don't recheck this puzzle state again later
        seen.append(current_puzzle)
        
        # Now we are going to add all the next actions to the to_visit array
        # If an action is valid, then we should add it to the array and also add the action to the path to that state

        # Up is implemented here
        up = slide_up(current_puzzle)
        if up is not False:
            to_visit.append((current_path + ('U',), up))
        
        # Your task is to implement all the other actions

        ''' Start of Answer '''
        ''' End of Answer '''
        
    
    print('No solution found')

Now that we have our Breadth-First Search Algorithm done, we should test it. Below are a few test cases, and also a random test for a 2 x 2 sliding tile puzzles. Try to create your own!

In [20]:
first = np.array([[3, 0], [2, 1]])
solved_first = bfs_sliding_tile(first)
print('First Sample:\n', first, '\nSolution:', solved_first)
assert(len(solved_first) == 5)

random_two_two = generate_valid_sliding_tile(2)
solved_two_two = bfs_sliding_tile(random_two_two)
print('Two by Two Sample:\n', random_two_two, '\nSolution:', solved_two_two)


# Now a Three-by-Three Test Case
second = np.array([[2, 3, 0], [1, 4, 6], [7, 5, 8]])
solved_second = bfs_sliding_tile(second)
print('Second Sample:\n', second, '\nSolution:', solved_second)
assert(len(solved_second) == 6)

First Sample:
 [[3 0]
 [2 1]] 
Solution: ('D', 'L', 'U', 'R', 'D')
Two by Two Sample:
 [[2 3]
 [0 1]] 
Solution: ('R', 'U', 'L', 'D', 'R')
Second Sample:
 [[2 3 0]
 [1 4 6]
 [7 5 8]] 
Solution: ('L', 'L', 'D', 'R', 'D', 'R')


If these test cases work, then congradulations you have finished part one of the assignment!

# Part 2

As you may have noticed, even though we are generating the correct solution it sometimes takes a very long time and won't even finish at all.

Let's take the following example

In [21]:
sliding_tile = np.array([[4, 2, 3], [7, 0, 5], [8, 6, 1]])
solved_sliding_tile = bfs_sliding_tile(sliding_tile)
print('Sliding Tile Sample:\n', sliding_tile, '\nSolution:', solved_sliding_tile)

If you have a computer like ours, this example will take really long to finish. Why is that?

Well, since we are exhaustively searching (using breadth-first-search) we must do every combination of actions before adding an action. This means that solutions that have larger depths (or require many actions) will take a very long time to complete, or may not complete at all.

Thus, we have to be a little smarter about how we search. We can't search everything because it takes to long.

A method to limit how long the searching takes is by using a heuristic. If we can judge how many more actions it will take for us to reach the solution, then we can search these paths first. Something to note is that this heuristic must be optimistic, or underestimate the number of moves it will take, as then we can still be guranteed to have the shortest possible path.

Lets experiment with creating a first heuristic for this problem. For this heuristic, we are just going to count the number of spots that are wrong. This underestimates the number of moves, as we must move these tiles in order to get a solution.

For example:

[[0 2]
 [3 1]]

will return 2. As 2,3 are in the right place and 0,1 are in the wrong place.

In [22]:
def out_of_place(puzzle):
    ''' Calculates the number of tiles out of place for the given puzzle '''
    num_out_of_place = 0
    ''' Start of Answer '''
    ''' End of Answer '''
    return num_out_of_place

Now that we have a heuristic, lets use it in our search algorithm. This algorithm is called A*-search, as it considers how far we have been and how far we must go to arrive at the solution. 

It follows the formula, F(N) = G(N) + H(N)

where, F is the estimate of the final distance, G is the current distance that we calculated, and H is the estimated further distance that we must go.

A* will search states with the lowest final distance first, before those with the longer distance. To do this, we are using a data structure called heap.

As this is a little more complicated, we have fully implemented it below

In [23]:
# A good default definition of a heap that we can use
import heapq
        
def astar_sliding_tile(puzzle, heuristic):
    ''' Performs a A* Search of the Sliding Tile Puzzle 
        Input: the puzzle to search, the heuristic to use
        Output: the path to the solution, number of states expanded'''
    
    seen = []

    # First create the heap
    to_visit = []
    heapq.heapify(to_visit)

    # Add our initial state
    heapq.heappush(to_visit, [0, 0, (), puzzle])

    num_expanded = 0
    while len(to_visit) > 0:
        # Get the current state of the puzzle
        _, _, current_path, current_puzzle = heapq.heappop(to_visit)
        
        # Check to see if the puzzle has been previously visited
        if check_if_in_array(seen, current_puzzle):
            continue

        # Check to see if the puzzle is solved
        if check_solved(current_puzzle):
            return current_path, num_expanded
        
        # count the number of expanded nodes that we have visited
        num_expanded += 1
        
        # Add the puzzle to the seen set
        seen.append(current_puzzle)
        
        # Add the puzzle's children to the to_visit queue
        up = slide_up(current_puzzle)
        if up is not False:
            new_path = current_path + ('U',)
            heapq.heappush(to_visit, [heuristic(up) + len(new_path), -1 * num_expanded, new_path, up])
        
        down = slide_down(current_puzzle)
        if down is not False:
            new_path = current_path + ('D',)
            heapq.heappush(to_visit, [heuristic(down) + len(new_path), -1 * num_expanded, new_path, down])
        
        left = slide_left(current_puzzle)
        if left is not False:
            new_path = current_path + ('L',)
            heapq.heappush(to_visit, [heuristic(left) + len(new_path), -1 * num_expanded, new_path, left])

        right = slide_right(current_puzzle)
        if right is not False:
            new_path = current_path + ('R',)
            heapq.heappush(to_visit, [heuristic(right) + len(new_path), -1 * num_expanded, new_path, right])
        
    print('No solution found')

Now let's solve the puzzle we had from earlier

In [24]:
sliding_tile = np.array([[4, 2, 3], [7, 0, 5], [8, 6, 1]])
solved_sliding_tile, expanded = astar_sliding_tile(sliding_tile, out_of_place)
print('Sliding Tile Sample:\n', sliding_tile, '\nSolution:', solved_sliding_tile, ' Expanded:', expanded)

Sliding Tile Sample:
 [[4 2 3]
 [7 0 5]
 [8 6 1]] 
Solution: ('R', 'D', 'L', 'L', 'U', 'R', 'R', 'U', 'L', 'D', 'L', 'U', 'R', 'R', 'D', 'D')  Expanded: 549


However, our heuristic only goes so far. You may still notice that we can't solve a random three-by-three sliding tile puzzle yet. For the rest of this project, your job is to find a heuristic function that can beat our simple out_of_place count.

What other estimates can you find that could estimate how much further better than we can?

In [ ]:
def your_heuristic(puzzle):
    ''' Start of Answer '''
    ''' End of Answer '''
    pass

sliding_tile = generate_valid_sliding_tile(4)
solved_sliding_tile, expanded = astar_sliding_tile(sliding_tile, your_heuristic)
print('Sliding Tile Sample:\n', sliding_tile, '\nSolution:', solved_sliding_tile, ' Expanded:', expanded)